include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

variables:
  STACK: etl
  IMAGE_NAME: apache/nifi
  IMAGE_TAG: latest
  STATUS_CHECK_DELAY: 300

.deploy:
  variables:
    SERVICES_TO_CHECK: ${STACK}_${CI_PROJECT_NAME}
  environment:
    url: https://${CI_PROJECT_NAME}.${PUBLIC_HOSTNAME}
