volumes:
  conf-vol:
    name: ${CONF_VOL_NAME}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${CONF_VOL_DEVICE:-:/nifi-conf-vol/}

  database-vol:
    name: ${DATABASE_VOL_NAME}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${DATABASE_VOL_DEVICE:-:/nifi-database-vol/}

  flowfile-vol:
    name: ${FLOWFILE_VOL_NAME}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${FLOWFILE_VOL_DEVICE:-:/nifi-flowfile-vol/}

  content-vol:
    name: ${CONTENT_VOL_NAME}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${CONTENT_VOL_DEVICE:-:/nifi-content-vol/}

  provenance-vol:
    name: ${PROVENANCE_VOL_NAME}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${PROVENANCE_VOL_DEVICE:-:/nifi-provenance-vol/}

  state-vol:
    name: ${STATE_VOL_NAME}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${STATE_VOL_DEVICE:-:/nifi-state-vol/}

  security-vol:
    name: ${SECURITY_VOL_NAME}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${SECURITY_VOL_DEVICE:-:/nifi-security-vol/}
