version: '3.7'

services:
  nifi:
    image: ${IMAGE_NAME:-apache/nifi}:${IMAGE_TAG:-latest}
    hostname: apache-nifi
    environment:
      NIFI_LOG_DIR:
      NIFI_HOME:
      NIFI_WEB_HTTP_HOST:
    networks:
      - traefik-net
    volumes:
      - nifi-log-vol:${NIFI_LOG_DIR}
      - nifi-conf-vol:${NIFI_HOME}/conf
      - nifi-database-vol:${NIFI_HOME}/database_repository
      - nifi-flowfile-vol:${NIFI_HOME}/flowfile_repository
      - nifi-content-vol:${NIFI_HOME}/content_repository
      - nifi-provenance-vol:${NIFI_HOME}/provenance_repository
      - nifi-state-vol:${NIFI_HOME}/state
      - ingest-data-vol:${NIFI_HOME}/data
    configs:
      - source: logback-xml
        target: ${NIFI_HOME}/conf/logback.xml
    healthcheck:
      test: curl --silent --output /dev/null http://apache-nifi:${PORT}/nifi
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5m
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 10s
        window: 2m
      labels:
        traefik.http.routers.nifi.entrypoints: https
        traefik.http.routers.nifi.rule: Host(`${SITE_SUBDOMAIN:-nifi}.${PUBLIC_HOSTNAME}`)
        traefik.http.services.nifi.loadbalancer.server.port: '${PORT}'
        traefik.http.routers.nifi.tls.certresolver: default
        traefik.http.middlewares.nifi-auth.basicauth.users: ${UI_AUTH}
        traefik.http.middlewares.nifi-headers.headers.customrequestheaders.X-ProxyScheme: https
        traefik.http.middlewares.nifi-headers.headers.customrequestheaders.X-ProxyHost: ${SITE_SUBDOMAIN:-nifi}.${PUBLIC_HOSTNAME}
        traefik.http.middlewares.nifi-headers.headers.customrequestheaders.X-ProxyPort: X-ProxyPort:443
        traefik.http.routers.nifi.middlewares: nifi-auth,nifi-headers

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

volumes:
  nifi-log-vol:
    name: ${NIFI_LOG_VOL_NAME:-nifi-log-vol}

  nifi-state-vol:
    name: ${NIFI_STATE_VOL_NAME:-nifi-state-vol}

  nifi-conf-vol:
    name: ${NIFI_CONF_VOL_NAME:-nifi-conf-vol}

  nifi-database-vol:
    name: ${NIFI_DATABASE_VOL_NAME:-nifi-database-vol}

  nifi-flowfile-vol:
    name: ${NIFI_FLOWFILE_VOL_NAME:-nifi-flowfile-vol}

  nifi-content-vol:
    name: ${NIFI_CONTENT_VOL_NAME:-nifi-content-vol}

  nifi-provenance-vol:
    name: ${NIFI_PROVENANCE_VOL_NAME:-nifi-provenance-vol}

  ingest-data-vol:
    name: ${INGEST_DATA_VOL_NAME:-ingest-data-vol}

configs:
  logback-xml:
    name: ${LOGBACK_XML_NAME:-nifi-logback-xml}
    file: ./config/logback.xml
