version: '3.5'

services:
  nifi:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 820M

volumes:
  nifi-conf-vol:
    name: ${NIFI_CONF_VOL_NAME:-nifi-conf-vol}

  nifi-database-vol:
    name: ${NIFI_DATABASE_VOL_NAME:-nifi-database-vol}

  nifi-flowfile-vol:
    name: ${NIFI_FLOWFILE_VOL_NAME:-nifi-flowfile-vol}

  nifi-content-vol:
    name: ${NIFI_CONTENT_VOL_NAME:-nifi-content-vol}

  nifi-provenance-vol:
    name: ${NIFI_PROVENANCE_VOL_NAME:-nifi-provenance-vol}

  nifi-additional-libs-vol:
    name: ${NIFI_ADDITIONAL_LIBS_VOL_NAME:-nifi-additional-libs-vol}

  ingest-data-vol:
    name: ${INGEST_DATA_VOL_NAME:-ingest-data-vol}
