version: '3.5'

services:
  nifi:
    image: apache/nifi:${IMAGE_TAG:-latest}
    networks:
      kafka-net:
      traefik-net:
    healthcheck:
      test: curl --silent http://localhost:${PORT}
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 2m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.frontend.auth.basic.users: ${UI_AUTH}
        traefik.frontend.rule: Host:nifi.${PUBLIC_HOSTNAME}
        traefik.backend: nifi
        traefik.port: "${PORT}"
      restart_policy:
        delay: 30s
        window: 2m
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 820M

networks:
  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true
