version: '3.9'

services:
  nifi:
    deploy:
      placement:
        constraints:
          - node.role == worker

volumes:
  conf-vol:
    name: ${CONF_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared

  database-vol:
    name: ${DATABASE_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared

  flowfile-vol:
    name: ${FLOWFILE_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: relocatable
      size: ${FLOWFILE_VOL_SIZE:-1}
      ebstype: gp3

  content-vol:
    name: ${CONTENT_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: relocatable
      size: ${CONTENT_VOL_SIZE:-5}
      ebstype: gp3

  provenance-vol:
    name: ${PROVENANCE_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: relocatable
      size: ${PROVENANCE_VOL_SIZE:-1}
      ebstype: gp3

  state-vol:
    name: ${STATE_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared

  security-vol:
    name: ${SECURITY_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared
