version: '3.5'

services:
  nifi:
    image: apache/nifi:${IMAGE_TAG:-latest}
    hostname: apache-nifi
    environment:
      - NIFI_LOG_DIR
      - NIFI_HOME
      - NIFI_WEB_HTTP_HOST
    networks:
      - traefik-net
      - kafka-net
    volumes:
      - nifi-log-vol:${NIFI_LOG_DIR}
      - nifi-conf-vol:${NIFI_HOME}/conf
      - nifi-database-vol:${NIFI_HOME}/database_repository
      - nifi-flowfile-vol:${NIFI_HOME}/flowfile_repository
      - nifi-content-vol:${NIFI_HOME}/content_repository
      - nifi-provenance-vol:${NIFI_HOME}/provenance_repository
      - nifi-state-vol:${NIFI_HOME}/state
    configs:
      - source: logback-xml
        target: ${NIFI_HOME}/conf/logback.xml
    healthcheck:
      test: curl --silent http://apache-nifi:${PORT}
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.frontend.auth.basic.users: ${UI_AUTH}
        traefik.frontend.rule: Host:nifi.${PUBLIC_HOSTNAME}
        traefik.frontend.headers.customRequestHeaders: X-ProxyScheme:https||X-ProxyHost:nifi.${PUBLIC_HOSTNAME}||X-ProxyPort:443
        traefik.backend: nifi
        traefik.port: "${PORT}"
      restart_policy:
        delay: 30s
        window: 2m

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    external: true

volumes:
  nifi-log-vol:
    name: ${NIFI_LOG_VOL_NAME:-nifi-log-vol}

  nifi-state-vol:
    name: ${NIFI_STATE_VOL_NAME:-nifi-state-vol}

configs:
  logback-xml:
    name: ${LOGBACK_XML_NAME:-nifi-logback-xml}
    file: ./config/logback.xml
