version: '3.5'

services:
  nifi:
    image: ${IMAGE_NAME:-apache/nifi}:${IMAGE_TAG:-latest}
    hostname: apache-nifi
    environment:
      HOME:
      NIFI_WEB_HTTP_HOST:
    networks:
      traefik-net:
      kafka-net:
      elastic-net:
    volumes:
      - log-vol:${HOME}/logs
      - conf-vol:${HOME}/conf
      - database-vol:${HOME}/database_repository
      - flowfile-vol:${HOME}/flowfile_repository
      - content-vol:${HOME}/content_repository
      - provenance-vol:${HOME}/provenance_repository
      - state-vol:${HOME}/state
      - ingest-vol:${HOME}/data
    configs:
      - source: logback-xml
        target: ${HOME}/conf/logback.xml
    healthcheck:
      test: curl --silent --output /dev/null http://apache-nifi:${PORT}/nifi
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-15s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-5m}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-10m}
      labels:
        traefik.frontend.auth.basic.users: ${UI_AUTH}
        traefik.frontend.rule: Host:${TRAEFIK_SUBDOMAIN}.${PUBLIC_HOSTNAME}
        traefik.frontend.headers.customRequestHeaders: X-ProxyScheme:https||X-ProxyHost:${TRAEFIK_SUBDOMAIN}.${PUBLIC_HOSTNAME}||X-ProxyPort:443||X-ProxyContextPath:/
        traefik.backend: nifi
        traefik.port: '${PORT}'

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    driver: ${KAFKA_NET_DRIVER:-overlay}
    external: true

  elastic-net:
    name: ${ELASTIC_NET_NAME:-elastic6-net}
    driver: ${ELASTIC_NET_DRIVER:-overlay}
    external: true

volumes:
  log-vol:
    name: ${LOG_VOL_NAME:-nifi-log-vol}

  state-vol:
    name: ${STATE_VOL_NAME:-nifi-state-vol}

configs:
  logback-xml:
    name: ${LOGBACK_XML_NAME:-nifi-logback-xml}
    file: ./config/logback.xml
